apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fabreviewccv1
  name: fabreviewccv1
  namespace: org1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fabreviewccv1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fabreviewccv1
    spec:
      containers:
      - env:
        # mandatory: in the format ${CHAINCODE_NAME}_${CHAINCODE_VERSION}:"sha256sum packaged_cc.tar.gz"
        # or obtain by running as admin: peer lifecycle chaincode queryinstalled
        - name: CHAINCODE_ID
          # edgeflare/fabric-chaincode helm chart creates a configmap with the package-id
          valueFrom:
            configMapKeyRef:
              key: package-id
              name: fabreviewccv1-package-id
        image: ghcr.io/edgeflare/fabreviewcc:1.0.0
        imagePullPolicy: Always
        name: fabreviewccv1
        ports:
        - containerPort: 7052
          protocol: TCP
        resources: {}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fabreviewccv1
  name: fabreviewccv1
  namespace: org1
spec:
  ports:
  - name: grpc
    port: 7052
    protocol: TCP
    targetPort: 7052
  selector:
    app.kubernetes.io/name: fabreviewccv1
  sessionAffinity: None
  type: ClusterIP
---
